export const ADD_BOARD = 'ADD_BOARD';
export const LOGIN = 'LOGIN';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESSFUL = 'GET_CURRENT_USER_SUCCESSFUL';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const FETCH_BOARD = 'FETCH_BOARD';
export const FETCH_BOARD_FULFILLED = 'FETCH_BOARD_FULFILLED';
export const LOGOUT = 'LOGOUT';
